version: "3.9"
services:
  timefs:
    extends:
      file: docker-compose-gui.yml
      service: timefs
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
